chain:
    bech32_prefix: bostrom
    modules:
        - modules
        - auth
        - bank
        - messages
        - graph
        - grid
        - resources
node:
    type: "remote"
    config:
        rpc:
            client_name: "cyberindex"
            max_connections: 10
            address: "http://localhost:26657"
        grpc:
            insecure: true
            address: "http://localhost:9090"
database:
    host: localhost
    max_idle_connections: 1
    max_open_connections: 1
    name: litvintech
    password: ""
    port: 5432
    schema: public
    user: litvintech
logging:
    format: text
    level: debug
parsing:
    listen_new_blocks: true
    parse_genesis: true
    parse_old_blocks: true
    start_height: 1
    workers: 1
